import React, { useEffect, useState } from 'react';
import { Image, Pressable, ScrollView, StyleSheet, Text, useWindowDimensions, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { DragDownDismiss } from '@/shared/components/DragDownDismiss';
import { Avatar } from '@/shared/components/Avatar';
import { useFeedStore } from '@/modules/feed/state/feed-store';
import { useChatStore } from '@/modules/chat/state/chat-store';
import { listingCondition, listingImage } from '../domain/secondhand-listing';
import { SecondhandListingMenu } from './SecondhandListingMenu';
import { trackBehavior } from '@/modules/profile/data/interestApi';

export function SecondhandDetailScreen() {
  const insets = useSafeAreaInsets();
  const { width } = useWindowDimensions();
  const { listingId } = useLocalSearchParams<{ listingId: string }>();
  const item = useFeedStore((state) => state.items.find((value) => value.id === listingId));
  const startChat = useChatStore((state) => state.startConversationWithCreator);
  const [menuVisible, setMenuVisible] = useState(false);
  useEffect(() => { if (item) void trackBehavior('SECONDHAND_VIEWED', { contentId: item.id, contentType: 'SECONDHAND', tags: item.product.tags ?? [], metadata: { location: item.location } }).catch(() => undefined); }, [item]);
  const dismiss = () => router.canGoBack() ? router.back() : router.replace('/(tabs)');
  if (!item) return <View style={styles.root}><Text style={styles.missing}>ไม่พบประกาศนี้</Text></View>;
  const images = item.imageUris?.length ? item.imageUris : listingImage(item) ? [listingImage(item)!] : [];
  const chat = () => { void trackBehavior('SELLER_CONTACTED', { contentId: item.id, contentType: 'SECONDHAND', tags: item.product.tags ?? [] }).catch(() => undefined); const id = startChat(item.author, item.authorHandle, item.gradient[1], { id: `secondhand-${item.id}`, feedId: item.id, title: item.product.name, subtitle: item.caption, price: item.product.basePrice, currency: 'THB', tier: 'C2C', imageUri: images[0], gradient: item.gradient, authorHandle: item.authorHandle, peerUserId: item.authorId }); router.push(`/(tabs)/chat/${encodeURIComponent(id)}`); };
  return <DragDownDismiss onDismiss={dismiss} style={styles.root}><View style={[styles.header, { paddingTop: insets.top }]}><Pressable onPress={dismiss} style={styles.back}><Ionicons name="close" size={26} color="#202824" /></Pressable><Text style={styles.headerTitle}>รายละเอียดสินค้า</Text><Pressable style={styles.back} onPress={() => setMenuVisible(true)}><Ionicons name="ellipsis-horizontal" size={24} color="#202824" /></Pressable></View><ScrollView contentContainerStyle={{ paddingBottom: insets.bottom + 100 }}><ScrollView horizontal pagingEnabled showsHorizontalScrollIndicator={false}>{images.map((uri) => <Image key={uri} source={{ uri }} style={[styles.hero, { width, height: width }]} resizeMode="cover" />)}</ScrollView><View style={styles.body}><Text style={styles.price}>฿{item.product.basePrice.toLocaleString('th-TH')}</Text><Text style={styles.title}>{item.product.name}</Text><View style={styles.tags}><Text style={styles.tag}>{listingCondition(item)}</Text><Text style={styles.location}><Ionicons name="location-outline" size={13} /> {item.location || 'ไม่ระบุพื้นที่'}</Text></View><Text style={styles.description}>{item.caption || 'ผู้ขายยังไม่ได้เพิ่มรายละเอียด'}</Text><Pressable style={styles.seller} onPress={() => item.isUserPost ? router.push('/(tabs)/profile') : router.push(`/creator/${encodeURIComponent(item.authorHandle.replace(/^@/, ''))}`)}><Avatar uri={item.authorAvatarUri} initial={item.author[0]} size={44} radius={22} /><View><Text style={styles.sellerName}>{item.author}</Text><Text style={styles.sellerMeta}>ผู้ขาย C2C</Text></View><Ionicons name="chevron-forward" size={20} color="#929B96" /></Pressable></View></ScrollView><View style={[styles.bottom, { paddingBottom: Math.max(insets.bottom, 10) }]}><Pressable style={styles.chat} onPress={chat}><Ionicons name="chatbubble-ellipses" size={21} color="#fff" /><Text style={styles.chatText}>แชตกับผู้ขาย</Text></Pressable></View><SecondhandListingMenu item={item} visible={menuVisible} onClose={() => setMenuVisible(false)} /></DragDownDismiss>;
}

const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: '#F4F6F4' }, header: { minHeight: 94, paddingHorizontal: 12, paddingBottom: 10, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', backgroundColor: '#fff' }, back: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center' }, headerTitle: { fontSize: 17, fontWeight: '900', color: '#202824', marginBottom: 10 }, hero: { backgroundColor: '#E5E9E6' }, body: { padding: 16 }, price: { color: '#E7354F', fontSize: 25, fontWeight: '900' }, title: { color: '#202824', fontSize: 21, lineHeight: 27, fontWeight: '900', marginTop: 4 }, tags: { flexDirection: 'row', gap: 10, alignItems: 'center', marginTop: 11 }, tag: { color: '#46514B', backgroundColor: '#E7EBE8', paddingHorizontal: 9, paddingVertical: 5, borderRadius: 8, fontSize: 11 }, location: { color: '#717B75', fontSize: 12 }, description: { color: '#46504A', fontSize: 15, lineHeight: 23, marginTop: 18 }, seller: { marginTop: 22, padding: 13, borderRadius: 17, backgroundColor: '#fff', flexDirection: 'row', alignItems: 'center', gap: 10 }, sellerName: { color: '#202824', fontSize: 14, fontWeight: '900' }, sellerMeta: { color: '#8A938E', fontSize: 11, marginTop: 2 }, bottom: { position: 'absolute', left: 0, right: 0, bottom: 0, paddingHorizontal: 14, paddingTop: 10, backgroundColor: '#fff' }, chat: { height: 52, borderRadius: 16, backgroundColor: '#202824', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 }, chatText: { color: '#fff', fontSize: 15, fontWeight: '900' }, missing: { marginTop: 140, textAlign: 'center', color: '#67716B' } });
